# Generated by Django 4.1.7 on 2023-03-01 08:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="Subject",
            new_name="subject",
        ),
    ]
