# Generated by Django 4.1.7 on 2023-03-01 10:45

import course.newfields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0003_video_text_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="content",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="module",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="content",
            name="order",
            field=course.newfields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="module",
            name="order",
            field=course.newfields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
